<template>
  <div class="design-helper-overlay" v-if="showDesignGuide">
    <!-- Zone Indicators -->
    <div class="zone-indicator faction-zone" data-zone="faction">
      <div class="zone-label">🏛️ FACTION ZONE (RED)</div>
      <div class="zone-description">
        Hiển thị faction được chọn<br>
        Size: 300x250px<br>
        Position: Top-Left
      </div>
    </div>

    <div class="zone-indicator characters-zone" data-zone="characters">
      <div class="zone-label">👥 CHARACTERS ZONE (BLUE)</div>
      <div class="zone-description">
        Navigation characters (max 3)<br>
        Size: Dynamic x 200px<br>
        Position: Top-Center
      </div>
    </div>

    <div class="zone-indicator lore-zone" data-zone="lore">
      <div class="zone-label">📖 LORE ZONE (YELLOW)</div>
      <div class="zone-description">
        Character story & info<br>
        Size: Dynamic x 200px<br>
        Position: Middle-Right
      </div>
    </div>

    <div class="zone-indicator skills-zone" data-zone="skills">
      <div class="zone-label">⚔️ SKILLS ZONE (GREEN)</div>
      <div class="zone-description">
        Character skills demo<br>
        Size: Full width x 150px<br>
        Position: Bottom
      </div>
    </div>

    <!-- Grid Overlay -->
    <div class="grid-overlay" v-if="showGrid"></div>

    <!-- Control Panel -->
    <div class="design-controls">
      <h4>🎯 Design Helper</h4>
      <button @click="showGrid = !showGrid" :class="{active: showGrid}">
        Grid {{ showGrid ? 'ON' : 'OFF' }}
      </button>
      <button @click="showMeasurements = !showMeasurements" :class="{active: showMeasurements}">
        Measurements
      </button>
      <button @click="exportCSS">📤 Export CSS</button>
      <button @click="showDesignGuide = false" class="close-btn">✕ Close</button>
    </div>

    <!-- Measurements -->
    <div class="measurements" v-if="showMeasurements">
      <div class="measurement-line horizontal" style="top: 100px; left: 0; right: 0;">
        <span class="measurement-label">100px from top</span>
      </div>
      <div class="measurement-line vertical" style="left: 350px; top: 100px; bottom: 100px;">
        <span class="measurement-label">350px from left</span>
      </div>
    </div>
  </div>

  <!-- Toggle Button -->
  <button 
    class="design-toggle-btn" 
    @click="showDesignGuide = !showDesignGuide"
    :class="{active: showDesignGuide}"
  >
    🎯 Design Guide
  </button>
</template>

<script>
export default {
  name: 'DesignHelper',
  data() {
    return {
      showDesignGuide: false,
      showGrid: true,
      showMeasurements: false
    }
  },
  methods: {
    exportCSS() {
      const css = `
/* Character Layout CSS - Generated by Design Helper */
.characters-layout {
  display: grid;
  grid-template-areas: 
    "faction characters characters"
    "lore lore lore" 
    "skills skills skills";
  grid-template-columns: 300px 1fr;
  grid-template-rows: 250px 200px 150px;
  gap: 20px;
  padding: 20px;
  min-height: 100vh;
}

.faction-area {
  grid-area: faction;
  background: rgba(220, 38, 127, 0.1);
  border: 2px solid #dc2626;
  border-radius: 15px;
  padding: 20px;
}

.character-nav-area {
  grid-area: characters;
  background: rgba(14, 165, 233, 0.1);
  border: 2px solid #0ea5e9;
  border-radius: 15px;
  padding: 20px;
}

.lore-area {
  grid-area: lore;
  background: rgba(34, 197, 94, 0.1);
  border: 2px solid #22c55e;
  border-radius: 15px;
  padding: 20px;
}

.skills-area {
  grid-area: skills;
  background: rgba(168, 85, 247, 0.1);
  border: 2px solid #a855f7;
  border-radius: 15px;
  padding: 20px;
}

/* Responsive */
@media (max-width: 768px) {
  .characters-layout {
    grid-template-areas:
      "faction"
      "characters"
      "lore" 
      "skills";
    grid-template-columns: 1fr;
    grid-template-rows: auto;
    gap: 15px;
    padding: 15px;
  }
}
      `;
      
      navigator.clipboard.writeText(css).then(() => {
        alert('✅ CSS đã được copy vào clipboard!');
      });
    }
  }
}
</script>

<style scoped>
.design-helper-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  pointer-events: none;
  z-index: 9999;
  background: rgba(0, 0, 0, 0.1);
}

.zone-indicator {
  position: absolute;
  border: 3px dashed;
  border-radius: 12px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  backdrop-filter: blur(2px);
  pointer-events: auto;
  cursor: pointer;
  transition: all 0.3s ease;
}

.zone-indicator:hover {
  transform: scale(1.02);
  backdrop-filter: blur(5px);
}

.faction-zone {
  top: 100px;
  left: 50px;
  width: 300px;
  height: 250px;
  border-color: #dc2626;
  background: rgba(220, 38, 127, 0.1);
  color: #dc2626;
}

.characters-zone {
  top: 100px;
  left: 370px;
  right: 370px;
  height: 200px;
  border-color: #0ea5e9;
  background: rgba(14, 165, 233, 0.1);
  color: #0ea5e9;
}

.lore-zone {
  top: 320px;
  left: 370px;
  right: 50px;
  height: 200px;
  border-color: #22c55e;
  background: rgba(34, 197, 94, 0.1);
  color: #22c55e;
}

.skills-zone {
  top: 540px;
  left: 50px;
  right: 50px;
  height: 150px;
  border-color: #a855f7;
  background: rgba(168, 85, 247, 0.1);
  color: #a855f7;
}

.zone-label {
  font-weight: bold;
  font-size: 16px;
  text-align: center;
  margin-bottom: 10px;
  text-transform: uppercase;
  letter-spacing: 1px;
}

.zone-description {
  font-size: 12px;
  text-align: center;
  line-height: 1.4;
  opacity: 0.9;
}

.grid-overlay {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-image: 
    linear-gradient(rgba(251, 191, 36, 0.2) 1px, transparent 1px),
    linear-gradient(90deg, rgba(251, 191, 36, 0.2) 1px, transparent 1px);
  background-size: 50px 50px;
  pointer-events: none;
}

.design-controls {
  position: fixed;
  top: 20px;
  right: 20px;
  background: rgba(0, 0, 0, 0.9);
  padding: 20px;
  border-radius: 12px;
  border: 2px solid #fbbf24;
  pointer-events: auto;
  min-width: 250px;
}

.design-controls h4 {
  color: #fbbf24;
  margin-bottom: 15px;
  text-align: center;
}

.design-controls button {
  background: rgba(251, 191, 36, 0.2);
  border: 1px solid #fbbf24;
  color: #fbbf24;
  padding: 8px 15px;
  margin: 5px;
  border-radius: 6px;
  cursor: pointer;
  font-size: 12px;
  transition: all 0.3s ease;
}

.design-controls button.active,
.design-controls button:hover {
  background: #fbbf24;
  color: #1a1a2e;
  font-weight: bold;
}

.close-btn {
  background: rgba(239, 68, 68, 0.2) !important;
  border-color: #ef4444 !important;
  color: #ef4444 !important;
}

.close-btn:hover {
  background: #ef4444 !important;
  color: white !important;
}

.design-toggle-btn {
  position: fixed;
  bottom: 20px;
  right: 20px;
  background: rgba(251, 191, 36, 0.9);
  color: #1a1a2e;
  border: none;
  padding: 12px 20px;
  border-radius: 25px;
  font-weight: bold;
  font-size: 14px;
  cursor: pointer;
  z-index: 1000;
  transition: all 0.3s ease;
  box-shadow: 0 4px 15px rgba(251, 191, 36, 0.3);
}

.design-toggle-btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 6px 20px rgba(251, 191, 36, 0.4);
}

.design-toggle-btn.active {
  background: #ef4444;
  color: white;
}

.measurements {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  pointer-events: none;
}

.measurement-line {
  position: absolute;
  border: 1px dashed #fbbf24;
}

.measurement-line.horizontal {
  height: 0;
}

.measurement-line.vertical {
  width: 0;
}

.measurement-label {
  position: absolute;
  background: rgba(0, 0, 0, 0.8);
  color: #fbbf24;
  padding: 2px 8px;
  border-radius: 4px;
  font-size: 11px;
  font-weight: bold;
  white-space: nowrap;
}

/* Responsive */
@media (max-width: 768px) {
  .design-controls {
    right: 10px;
    top: 10px;
    min-width: 200px;
    padding: 15px;
  }
  
  .design-toggle-btn {
    bottom: 10px;
    right: 10px;
    padding: 10px 15px;
    font-size: 12px;
  }
  
  .zone-indicator {
    font-size: 12px;
  }
  
  .zone-label {
    font-size: 14px;
  }
  
  .zone-description {
    font-size: 10px;
  }
}
</style>